version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "jest",
    "cypress"
  ]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "test-coverage"